[package]
name = "random-desktop-image"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
rand = "0.9.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
